### ISSUE TITLE
[Usability] Function headings are not clear

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#419]
I am having a hard time trying to spot where the functions begin.
I think we need to make clear where a function ends and where a new one starts..
Please, have a look at this screenshot.
![ex_doc_fuction_heading](https://cloud.githubusercontent.com/assets/9133420/9976744/0f1d8f00-5f17-11e5-89ee-6b3f18e9ce9a.png)

I know where Example Starts,
and the second Example begins.
but to my tired eyes, it looks like **intersperse** belongs to the top Example, when it is sort of the opposite.

WDYGT

**Comment by josevalim** [comment]
Others have mentioned this too. One approach is to reduce the headers size inside the functions themselves.

**Comment by Dignifiedquire** [comment]
I think the solution is two fold. First reduce the size of headers like `Examples` to the same size as `Specs`, second add some indentation of the content inside the function block so the function header stands out more

**Comment by eksperimental** [comment]
seriously combining this issue with the fact that visiting the internal links from the search does not take you exactly where it should, It's impossible to spot the functions.. i end up going to the sidebar and clicking there.

one solution, maybe is give move white space after each funcion.
another... maybe it won't look good, but it can be something along those lines.. is to extend the blueish block so it sticks out to the left marging so  it can help you visually identify where these function headings are..

**Comment by eksperimental** [comment]
a solid horizantal divider ala `<HR>`, may help as well. sorry guys. my designing skills are horrible. ;-P

**Comment by josevalim** [comment]
@Dignifiedquire we need to support h1 + h2 (they could have exactly the same size as docs are not meant to have h1), h3 and h4.

**Comment by DanCouper** [comment]
Just to add to the discussion, I'd agree with @eksperimental on all counts. Here are two secreenshots:

![exdocs-zoomedin](https://cloud.githubusercontent.com/assets/573694/10097267/e29b7f84-636f-11e5-906b-75c44832ebf8.png)

![exdocs-zoomedout](https://cloud.githubusercontent.com/assets/573694/10097268/e29e063c-636f-11e5-8d2d-c49ef04f20d3.png)

I'm reiterating points, but there a. isn't enough whitespace between the function sections (and a horizontal divider may be helpful *in addition to* increasing the gap), and b. the headers don't delimit the sections properly - they simply don't stand out compared to the headers for the examples, which makes scan-reading very difficult. I'd extend this criticism to the @moduledoc section, and the generated summary - there isn't enough typographic/layout differentiation between the different module sections, and at a more granular level between the sections under each function. It's just about there, and it's beautiful, but they currently aren't as easy to quickly scan as the original, much uglier docs.

**Comment by josevalim** [comment]
The spacing suggestion is a good one. Adding the spacing and reducing the headers font-size will be likely enough to solve this completely. :D

**Comment by DanCouper** [comment]
I'd agree with that :)

**Comment by eksperimental** [comment]
one good point that @DanCouper  made is that the function HEADER, looks like inline code.
having a background color similar to the ones in the code examples make it difficult to stand out.
maybe with a bigger font, it won't look like code anymore.. we'll see

**Comment by edmz** [comment]
I was just going to submit an issue for this. Its good to realize that I am not the only one for who this is important. 

My gripes have already been addressed here by eksperimental and dancouper.

**Comment by eksperimental** [comment]
@milmazz what I meant what, now that I read back is exactly what @Dignifiedquire proposed earlier:
> I think the solution is two fold. First reduce the size of headers like Examples to the same size as Specs, second add some indentation of the content inside the function block so the function header stands out more

![indented](https://cloud.githubusercontent.com/assets/9133420/11274507/c5805b3c-8f0b-11e5-98de-1ad7c0dccb5e.png)

While it definitely  looks much better now after the changes, I think we still have the issue of having the function heading not clearly distinguishable.
As I mentioned before, having the same color as the code style, makes it difficult to stand out on its own. Specially when the previous function ends in code example as it is with most of the cases in the Kernel module. And I'm not to sure if indenting would suffice. 

I would also wait for a bit to close this issue until we have agreed to have a solution.

**Comment by edmz** [comment]
+1 on the indentation.

Also, I think that the colors (the light blue and the gray) are inverted. At least for me, the blue stands out more, thus, giving more importance to the spec and the code example while the function name seems secondary.

Example of inverting colors:

<img width="771" alt="screen shot 2015-11-19 at 10 05 52 am" src="https://cloud.githubusercontent.com/assets/18996/11275898/5590fe50-8ea5-11e5-9c3e-2f8dee7f8ffd.png">'

(also, some vertical space between functions might help a bit too)

**Comment by endersstocker** [comment]
@eksperimental Your last screenshot looks good. I would increase the vertical gap though.

**Comment by josevalim** [comment]
@eksperimental please create a new issue and copy @Dignifiedquire :)
