### ISSUE TITLE
Slow scrolling on Safari for macOS 10.13 due to additional style rule

### ISSUE THREAD

**Issue by evadne** [elixir-lang/ex_doc#851]
The page https://hexdocs.pm/mix/Mix.Tasks.Profile.Fprof.html scrolls very slowly (20fps – 30fps) on rMBP 2016 when integrated graphics is used on Safari 11.1 (13605.1.33.1.4) for macOS 10.13 due to this rule:

    .content-inner .specs pre, .content-inner code {
      font-family: Inconsolata,Menlo,Courier,monospace;
    }

When scrolling up/down the frame rate drops to 30fps. Unfortunately when recording screen content with QuickTime Player the frame rate is capped at 30fps anyway. But disabling this particular rule in Inspector restores performance (55fps – 60fps).

**Comment by josevalim** [comment]
Thanks @evadne! I could not reproduce on Safari 11.1.1. Can you?

**Comment by josevalim** [comment]
Ping. :)

**Comment by net** [comment]
Same behavior for me on both 11.1.1 and 12.0. I agree it is likely a Safari bug; however, it may still be worth considering a interim patch.

**Comment by josevalim** [comment]
Thanks @net! Since I cannot reproduce it locally, could you take a look at it and see if you can come up with a fix?

**Comment by michalmuskala** [comment]
I can reproduce this, but disabling the style rule that @evadne pointed out does not fix it for me.

**Comment by smfr** [comment]
Slow scrolling triggered by certain fonts was fixed in macOS Mojave.

**Comment by josevalim** [comment]
Glad to hear!

**Comment by josevalim** [comment]
Thanks for the updates!

**Comment by evadne** [comment]
Hi, on 10.13 this still happens somehow if the window is larger, I can get it to lag on a Vega 64 when the window is 1920 by 2160 pixels. I have done some poking around today, and found that this is likely because the sidebar and content elements are overlapping. The content element sits under the sidebar and has `width: 100%; padding-left: 300px`. I have tried to change this to `width: calc(100% - 300px)` and it seems much better now.

**Comment by kzvi** [comment]
Just for the record I still have this issue on Mojave.

**Comment by archdragon** [comment]
I have a theory about where the problem might be. I've tried to reproduce and fix it locally.

@evadne @kzvi If you have a moment can you take a look at:
1) [My demo](http://krowinski.com/ex_doc/safari_scroll/Kernel.html)
2) [Hexdocs](https://hexdocs.pm/elixir/Kernel.html)

and check if you see any difference between 1) and 2) ? 

Thanks! :)

**Comment by smfr** [comment]
https://hexdocs.pm/elixir/Kernel.html is slow because it's using overflow:scroll. Your demo is faster because it's using page scrolling, which is more highly optimized in Safari.
